<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita07544ac7a0f857e0e4fdf5e08643843
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita07544ac7a0f857e0e4fdf5e08643843::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita07544ac7a0f857e0e4fdf5e08643843::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita07544ac7a0f857e0e4fdf5e08643843::$classMap;

        }, null, ClassLoader::class);
    }
}
